"""fix_trainer_fk_cascades

Revision ID: a6249e4c9b28
Revises: 877808ca47ef
Create Date: 2026-02-22 02:23:25.648948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6249e4c9b28'
down_revision: Union[str, None] = '877808ca47ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('brain_messages_trainer_id_fkey'), 'brain_messages', type_='foreignkey')
    op.create_foreign_key(None, 'brain_messages', 'trainers', ['trainer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('session_plans_trainer_id_fkey'), 'session_plans', type_='foreignkey')
    op.create_foreign_key(None, 'session_plans', 'trainers', ['trainer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_trainer_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'trainers', ['trainer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_trainer_id_fkey'), 'sessions', 'trainers', ['trainer_id'], ['id'])
    op.drop_constraint(None, 'session_plans', type_='foreignkey')
    op.create_foreign_key(op.f('session_plans_trainer_id_fkey'), 'session_plans', 'trainers', ['trainer_id'], ['id'])
    op.drop_constraint(None, 'brain_messages', type_='foreignkey')
    op.create_foreign_key(op.f('brain_messages_trainer_id_fkey'), 'brain_messages', 'trainers', ['trainer_id'], ['id'])
    # ### end Alembic commands ###
