"""add planned_exercises JSONB to session_plans

Revision ID: c7924255a8da
Revises: fcc11556fbfe
Create Date: 2026-04-16 09:47:56.073106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7924255a8da'
down_revision: Union[str, None] = 'fcc11556fbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_plans', sa.Column('planned_exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_plans', 'planned_exercises')
    # ### end Alembic commands ###
