"""add_preferred_weight_unit_to_clients

Revision ID: fcc11556fbfe
Revises: a6249e4c9b28
Create Date: 2026-02-24 18:51:30.952888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc11556fbfe'
down_revision: Union[str, None] = 'a6249e4c9b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('preferred_weight_unit', sa.String(length=10), server_default='kg', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'preferred_weight_unit')
    # ### end Alembic commands ###
